-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 19:22:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotelManagementDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS hotelManagementDB;
CREATE DATABASE IF NOT EXISTS hotelManagementDB;
USE hotelManagementDB;

-- -----------------------------------------------------
-- Table `Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Owner` ;

CREATE TABLE IF NOT EXISTS `Owner` (
  `ownerId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`ownerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revenue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Revenue` ;

CREATE TABLE IF NOT EXISTS `Revenue` (
  `revenueId` INT NOT NULL,
  `total` FLOAT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`revenueId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Power Generator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Power Generator` ;

CREATE TABLE IF NOT EXISTS `Power Generator` (
  `generatorId` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`generatorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fire Alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fire Alarm` ;

CREATE TABLE IF NOT EXISTS `Fire Alarm` (
  `fAlarmId` INT NOT NULL,
  `activated` TINYINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fAlarmId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Security Alarm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Security Alarm` ;

CREATE TABLE IF NOT EXISTS `Security Alarm` (
  `securityId` INT NOT NULL,
  `activated` TINYINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`securityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pool` ;

CREATE TABLE IF NOT EXISTS `Pool` (
  `poolId` INT NOT NULL,
  `depth` INT NOT NULL,
  `isIndoor` TINYINT NOT NULL,
  PRIMARY KEY (`poolId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hotel` ;

CREATE TABLE IF NOT EXISTS `Hotel` (
  `hotelId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `rating` INT NULL,
  `addressId` INT NOT NULL,
  `ownerId` INT NOT NULL,
  `revenueId` INT NULL,
  `generatorId` INT NOT NULL,
  `fAlarmId` INT NOT NULL,
  `securityId` INT NOT NULL,
  `poolId` INT NOT NULL,
  PRIMARY KEY (`hotelId`),
  INDEX `fk_Hotel_Owner1_idx` (`ownerId` ASC) ,
  INDEX `fk_Hotel_Revenue1_idx` (`revenueId` ASC) ,
  INDEX `fk_Hotel_Power Generator1_idx` (`generatorId` ASC) ,
  INDEX `fk_Hotel_Fire Alarm1_idx` (`fAlarmId` ASC) ,
  INDEX `fk_Hotel_Security Alarm1_idx` (`securityId` ASC) ,
  UNIQUE INDEX `addressId_UNIQUE` (`addressId` ASC) ,
  UNIQUE INDEX `revenueId_UNIQUE` (`revenueId` ASC) ,
  INDEX `fk_Hotel_Pool1_idx` (`poolId` ASC) ,
  CONSTRAINT `hotel_owner_FK`
    FOREIGN KEY (`ownerId`)
    REFERENCES `Owner` (`ownerId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_revenue_FK_UQ`
    FOREIGN KEY (`revenueId`)
    REFERENCES `Revenue` (`revenueId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_generator_FK`
    FOREIGN KEY (`generatorId`)
    REFERENCES `Power Generator` (`generatorId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_fAlarm_FK`
    FOREIGN KEY (`fAlarmId`)
    REFERENCES `Fire Alarm` (`fAlarmId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_security_FK`
    FOREIGN KEY (`securityId`)
    REFERENCES `Security Alarm` (`securityId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `hotel_pool_FK`
    FOREIGN KEY (`poolId`)
    REFERENCES `Pool` (`poolId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Expenditures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Expenditures` ;

CREATE TABLE IF NOT EXISTS `Expenditures` (
  `expendituresId` INT NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `date` DATE NOT NULL,
  `hotelId` INT NOT NULL,
  PRIMARY KEY (`expendituresId`),
  INDEX `fk_Expenditures_Hotel1_idx` (`hotelId` ASC) ,
  CONSTRAINT `expenditures_hotel_FK`
    FOREIGN KEY (`hotelId`)
    REFERENCES `Hotel` (`hotelId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fire Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fire Department` ;

CREATE TABLE IF NOT EXISTS `Fire Department` (
  `fireDepartmentId` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `fAlarmId` INT NULL,
  PRIMARY KEY (`fireDepartmentId`),
  INDEX `fk_Fire Department_Fire Alarm1_idx` (`fAlarmId` ASC) ,
  UNIQUE INDEX `fAlarmId_UNIQUE` (`fAlarmId` ASC) ,
  CONSTRAINT `fDepartment_fAlarm_FK_UQ`
    FOREIGN KEY (`fAlarmId`)
    REFERENCES `Fire Alarm` (`fAlarmId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Police Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Police Station` ;

CREATE TABLE IF NOT EXISTS `Police Station` (
  `policeId` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `securtiyId` INT NULL,
  PRIMARY KEY (`policeId`),
  INDEX `fk_Police Station_Security Alarm1_idx` (`securtiyId` ASC) ,
  UNIQUE INDEX `securtiyId_UNIQUE` (`securtiyId` ASC) ,
  CONSTRAINT `station_security_FK_UQ`
    FOREIGN KEY (`securtiyId`)
    REFERENCES `Security Alarm` (`securityId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `addressId` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `departmentId` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `numEmployee` INT NOT NULL,
  PRIMARY KEY (`departmentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employeeId` INT NOT NULL,
  `isManager` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `wage` DECIMAL(18,2) NOT NULL,
  `age` INT NOT NULL,
  `hotelId` INT NOT NULL,
  `departmentId` INT NULL,
  PRIMARY KEY (`employeeId`),
  INDEX `fk_Employee_Hotel1_idx` (`hotelId` ASC) ,
  INDEX `fk_Employee_Department1_idx` (`departmentId` ASC) ,
  CONSTRAINT `employee_hotel_FK`
    FOREIGN KEY (`hotelId`)
    REFERENCES `Hotel` (`hotelId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `employee_department_FK`
    FOREIGN KEY (`departmentId`)
    REFERENCES `Department` (`departmentId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurant Employee` ;

CREATE TABLE IF NOT EXISTS `Restaurant Employee` (
  `restaurantId` INT NOT NULL,
  `isChef` TINYINT NOT NULL,
  `isServer` TINYINT NOT NULL,
  `employeeId` INT NOT NULL,
  PRIMARY KEY (`restaurantId`, `employeeId`),
  INDEX `employeeId_idx` (`employeeId` ASC) ,
  CONSTRAINT `restaurant_employee_FK_PK`
    FOREIGN KEY (`employeeId`)
    REFERENCES `Employee` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Booking` ;

CREATE TABLE IF NOT EXISTS `Booking` (
  `bookingId` INT NOT NULL,
  `dateMade` DATE NOT NULL,
  `bookingDate` DATE NOT NULL,
  PRIMARY KEY (`bookingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Room Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Room Class` ;

CREATE TABLE IF NOT EXISTS `Room Class` (
  `classId` INT NOT NULL,
  `oneBed` TINYINT NOT NULL,
  `twoBed` TINYINT NOT NULL,
  `suite` TINYINT NOT NULL,
  `penthouse` TINYINT NOT NULL,
  PRIMARY KEY (`classId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Room` ;

CREATE TABLE IF NOT EXISTS `Room` (
  `roomId` INT NOT NULL,
  `roomNumber` INT NOT NULL,
  `availability` TINYINT NOT NULL,
  `costPerNight` DECIMAL NOT NULL,
  `hotelId` INT NOT NULL,
  `bookingId` INT NULL,
  `classId` INT NOT NULL,
  PRIMARY KEY (`roomId`),
  INDEX `fk_Room_Hotel1_idx` (`hotelId` ASC) INVISIBLE,
  INDEX `fk_Room_Booking1_idx` (`bookingId` ASC) ,
  UNIQUE INDEX `Booking_bookingId_UNIQUE` (`bookingId` ASC) ,
  INDEX `fk_Room_Room Class1_idx` (`classId` ASC) ,
  CONSTRAINT `room_hotel_FK`
    FOREIGN KEY (`hotelId`)
    REFERENCES `Hotel` (`hotelId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `room_booking_FK_UQ`
    FOREIGN KEY (`bookingId`)
    REFERENCES `Booking` (`bookingId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `room_class_FK`
    FOREIGN KEY (`classId`)
    REFERENCES `Room Class` (`classId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Front Desk Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Front Desk Employee` ;

CREATE TABLE IF NOT EXISTS `Front Desk Employee` (
  `employeeId` INT NOT NULL,
  `roomId` INT NULL,
  `isGraveyard` TINYINT NOT NULL,
  PRIMARY KEY (`employeeId`),
  INDEX `employeeId_idx` (`employeeId` ASC) ,
  INDEX `roomId_idx` (`roomId` ASC) ,
  CONSTRAINT `desk_employee_FK_PK`
    FOREIGN KEY (`employeeId`)
    REFERENCES `Employee` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `desk_room_FK_UQ`
    FOREIGN KEY (`roomId`)
    REFERENCES `Room` (`roomId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `House Keeping Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `House Keeping Employee` ;

CREATE TABLE IF NOT EXISTS `House Keeping Employee` (
  `employeeId` INT NOT NULL,
  `roomId` INT NULL,
  `isCleaner` TINYINT NOT NULL,
  `isRestocker` TINYINT NOT NULL,
  PRIMARY KEY (`employeeId`),
  INDEX `employeeId_idx` (`employeeId` ASC) ,
  INDEX `roomId_idx` (`roomId` ASC) ,
  UNIQUE INDEX `roomId_UNIQUE` (`roomId` ASC) ,
  CONSTRAINT `house_employee_FK_PK`
    FOREIGN KEY (`employeeId`)
    REFERENCES `Employee` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `house_room_FK_UQ`
    FOREIGN KEY (`roomId`)
    REFERENCES `Room` (`roomId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplier` ;

CREATE TABLE IF NOT EXISTS `Supplier` (
  `supplierId` INT NOT NULL,
  `restockDate` DATE NOT NULL,
  `cost` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `paymentId` INT NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `date` DATE NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paymentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Register`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Register` ;

CREATE TABLE IF NOT EXISTS `Register` (
  `registerId` INT NOT NULL,
  `cost` DECIMAL(18,2) NOT NULL,
  `date` DATE NOT NULL,
  `paymentId` INT NULL,
  PRIMARY KEY (`registerId`),
  INDEX `fk_Register_Payment1_idx` (`paymentId` ASC) ,
  UNIQUE INDEX `paymentId_UNIQUE` (`paymentId` ASC) ,
  CONSTRAINT `register_payment_FK_UQ`
    FOREIGN KEY (`paymentId`)
    REFERENCES `Payment` (`paymentId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Item` ;

CREATE TABLE IF NOT EXISTS `Item` (
  `itemId` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `dateAcquired` DATE NOT NULL,
  `supplierId` INT NOT NULL,
  `registerId` INT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `fk_Item_Supplier1_idx` (`supplierId` ASC) ,
  INDEX `fk_Item_Register1_idx` (`registerId` ASC) ,
  CONSTRAINT `item_supplier_FK`
    FOREIGN KEY (`supplierId`)
    REFERENCES `Supplier` (`supplierId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_register_FK_UQ`
    FOREIGN KEY (`registerId`)
    REFERENCES `Register` (`registerId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Food` ;

CREATE TABLE IF NOT EXISTS `Food` (
  `itemId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(18,2) NOT NULL,
  `instock` TINYINT NOT NULL,
  INDEX `itemId_idx` (`itemId` ASC) ,
  PRIMARY KEY (`itemId`),
  CONSTRAINT `food_item_FK_PK`
    FOREIGN KEY (`itemId`)
    REFERENCES `Item` (`itemId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Beverage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Beverage` ;

CREATE TABLE IF NOT EXISTS `Beverage` (
  `itemId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(18,2) NOT NULL,
  `instock` TINYINT NOT NULL,
  INDEX `itemId_idx` (`itemId` ASC) ,
  PRIMARY KEY (`itemId`),
  CONSTRAINT `beverage_item_FK_PK`
    FOREIGN KEY (`itemId`)
    REFERENCES `Item` (`itemId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Misc Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Misc Item` ;

CREATE TABLE IF NOT EXISTS `Misc Item` (
  `itemId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(18,2) NOT NULL,
  `inStock` TINYINT NOT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `itemId_idx` (`itemId` ASC) ,
  CONSTRAINT `misc_item_FK_PK`
    FOREIGN KEY (`itemId`)
    REFERENCES `Item` (`itemId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Invoice` ;

CREATE TABLE IF NOT EXISTS `Invoice` (
  `invoiceId` INT NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`invoiceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

CREATE TABLE IF NOT EXISTS `Customer` (
  `customerId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `bookingId` INT NOT NULL,
  `invoiceId` INT NULL,
  `paymentId` INT NULL,
  `hotelId` INT NULL,
  PRIMARY KEY (`customerId`),
  INDEX `fk_Customer_Booking1_idx` (`bookingId` ASC) ,
  INDEX `fk_Customer_Invoice1_idx` (`invoiceId` ASC) ,
  INDEX `fk_Customer_Payment1_idx` (`paymentId` ASC) ,
  UNIQUE INDEX `invoiceId_UNIQUE` (`invoiceId` ASC) ,
  UNIQUE INDEX `paymentId_UNIQUE` (`paymentId` ASC) ,
  INDEX `fk_Customer_Hotel1_idx` (`hotelId` ASC) ,
  CONSTRAINT `customer_booking_FK`
    FOREIGN KEY (`bookingId`)
    REFERENCES `Booking` (`bookingId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `customer_invoice_FK_UQ`
    FOREIGN KEY (`invoiceId`)
    REFERENCES `Invoice` (`invoiceId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `customer_payment_FK_UQ`
    FOREIGN KEY (`paymentId`)
    REFERENCES `Payment` (`paymentId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `customer_hotel_FK_UQ`
    FOREIGN KEY (`hotelId`)
    REFERENCES `Hotel` (`hotelId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodMade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodMade` ;

CREATE TABLE IF NOT EXISTS `FoodMade` (
  `restaurantId` INT NOT NULL,
  `foodId` INT NOT NULL,
  PRIMARY KEY (`restaurantId`, `foodId`),
  INDEX `fk_Restaurant Employee_has_Food_Food1_idx` (`foodId` ASC) ,
  CONSTRAINT `made_restaurantFK_PK`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `Restaurant Employee` (`restaurantId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `made_foodFK_PK`
    FOREIGN KEY (`foodId`)
    REFERENCES `Food` (`itemId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeesManaged`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmployeesManaged` ;

CREATE TABLE IF NOT EXISTS `EmployeesManaged` (
  `managerId` INT NOT NULL,
  `houseKeepingId` INT NULL,
  `restaurantId` INT NULL,
  `deskId` INT NULL,
  PRIMARY KEY (`managerId`),
  INDEX `fk_Manages_House Keeping Employee1_idx` (`houseKeepingId` ASC) ,
  INDEX `fk_Manages_Restaurant Employee1_idx` (`restaurantId` ASC) ,
  INDEX `fk_Manages_Front Desk Employee1_idx` (`deskId` ASC) ,
  UNIQUE INDEX `House Keeping Employee_employeeId_UNIQUE` (`houseKeepingId` ASC) ,
  UNIQUE INDEX `Restaurant Employee_employeeId_UNIQUE` (`restaurantId` ASC) ,
  UNIQUE INDEX `Front Desk Employee_employeeId_UNIQUE` (`deskId` ASC) ,
  UNIQUE INDEX `managerId_UNIQUE` (`managerId` ASC) ,
  CONSTRAINT `manageed_manager_FK_PK`
    FOREIGN KEY (`managerId`)
    REFERENCES `Employee` (`employeeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `manageed_house_FK_UQ`
    FOREIGN KEY (`houseKeepingId`)
    REFERENCES `House Keeping Employee` (`employeeId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `manageed_restaurant_FK_UQ`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `Restaurant Employee` (`employeeId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `manageed_desk_FK_UQ`
    FOREIGN KEY (`deskId`)
    REFERENCES `Front Desk Employee` (`employeeId`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
